services:
  kong-gateway:
    image: kong/kong-gateway:3.7.1.2
    container_name: kong-dbless
    networks:
      - kong-net
    volumes:
      - ./:/kong/declarative/
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004

  account-manager-service:
    build:
      context: ./account-manager-service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mynet
      - kong-net
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
      DIRECT_URL: postgres://user:password@postgres:5432/mydatabase
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3aW5rZ2NsdHNhcG9iY2hnZ3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM5NTM4NzEsImV4cCI6MjAzOTUyOTg3MX0.mc1ROHgdAvEGb9Ss4EUoPJfQpONKM3rbYPXOdomy3Gs
      SUPABASE_URL: https://lwinkgcltsapobchggvw.supabase.co
      SUPABASE_JWT_SECRET: mgReFIAmY4diZkZEl7+jK4pRviZt6WyljASEACoB5fgwAgIEAUq1U9/Qj8qGcAc06b0Iu8qmpJLwFa/A5HZNAg==
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure

  payment-manager-service:
    build:
      context: ./payment-manager-service
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - mynet
      - kong-net
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
      DIRECT_URL: postgres://user:password@postgres:5432/mydatabase
      SUPABASE_JWT_SECRET: mgReFIAmY4diZkZEl7+jK4pRviZt6WyljASEACoB5fgwAgIEAUq1U9/Qj8qGcAc06b0Iu8qmpJLwFa/A5HZNAg==
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    restart: always
    networks:
      - mynet
      - kong-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  mynet:
    driver: bridge
  kong-net:
    driver: bridge

volumes:
  postgres-data:
